### ISSUE TITLE
Just get a white screen

### ISSUE THREAD

**Issue by row1** [Infinest/GB-Memory-Binary-Maker#2]
Has this been tested to still work on Windows 10? Any generated .gb binaries do not work for me in an emulator or on an actual device. In both cases it just results in a white screen (the emulator gives a checksum error).

I have tried small and larger ROMs. On the Windows 10 Pro 1803.

**Comment by Infinest** [comment]
Emulators spitting out a warning about an incorrect checksum is normal.
The program isn't currently correcting the checksum of the ROM after generating it. That doesn't stop the ROM from working on a real Game Boy or an emulator though.
I haven't tested it on Windows 10 as i'm still on Windows 7 but I highly doubt your Os is at fault.

So, first question: At what point are you encountering the white screen? Immediately on boot-up or after selecting a game in the menu? If you get a white screen immediately on boot-up my first guess would be that you're not using a proper dump of the carts menu.
Here's hashes for two working publicly available dumps (SHA-256):
- 4C3ACC284FE8119AA0F67CA720CDA0AFB83EB6425F12A739CF3928BBD4CDF0D1
- DAA2DED60E6F8E8A2EEC0D949E5F3C6352EC67463C31BB00964E2D6D4AA39C21

If you're getting a white screen after selecting a game then that's normal on emulators. I don't know any emulator that correctly emulates the correct behavior of the cart's mapper + the map binary.
If you're experiencing this on a real cartridge then you probably forgot to burn or didn't properly burn the map file that the program spits out together with the  normal ROM.
Do you have the proper hardware to burn the map file to your cartridge? As far as i'm aware the only device that's widely available and able to properly do this is https://github.com/sanni/cartreader

**Comment by row1** [comment]
I am encountering the white screen immediately on boot, both in the emulator and when burnt onto a cart.

I have dumped my own menu and also tried a known menu supplied by insidegadgets. The menu .gb file loads fine in an emulator. I can also write the original menu (.gb + .map) back to the cart and it loads fine.

I am using gbxcart-rw which supports burning it.

**Comment by row1** [comment]
Sorry looks like menu.gb was the issue. Have tried dumping the menu again and it works now (get a different hash to the two you supplied though...). Thanks

**Comment by Infinest** [comment]
Great to hear it was solved.
The different hashes are probably a result of the different news ticker strings the menu ROMs contain.
Nothing to worry about as long as it works
