### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by epbarger** [Infinest/GB-Memory-Binary-Maker#3]
I'm interested in the MBC2 support and other bugfixes that have been added since the last release, maybe it's time for a forth release?

**Comment by Infinest** [comment]
I've gone ahead and compiled the current sources.
Here's the release:
https://github.com/Infinest/GB-Memory-Binary-Maker/releases/tag/v1.1.3

**Comment by epbarger** [comment]
Thank you!
