### ISSUE TITLE
Mapping error

### ISSUE THREAD

**Issue by nensondubois** [Infinest/GB-Memory-Binary-Maker#4]
As of version 1.1.3.0 games do not write properly if several or more 128kb MBC1 games are selected and if 256kb or more are also on the same cart. The program will not write a working GB Memory rom, but instead gives an unhanded exception.

**Comment by Infinest** [comment]
Could you give a step by step guide on what you did + a screenshot?
The list of games + their file hashes would also be helpful.
I might have misunderstood you but this is the current setup I have and it's working for me:
![image](https://i.imgur.com/iaBm9lC.png)

**Comment by nensondubois** [comment]
Apparently the issue is related to an older version of the "GBS PLAYER 3U" This is an example of a problematic header starting at 0x0120-0160. "DDDDD999BBBB67636E0EECCCDDDC999FBBB9333E47425320504C415920312E3033552080535700010200013302FBB2D7F3E080CD8800215C3F2A666FF92104002A5F2A57B328102A4F2A23232323E569". There may be other incompatible games with other mappers though support isn't expected since the GB Memory cart does not contain the chipsets without converting games to other mappers.

**Comment by nensondubois** [comment]
Also, this gives an error as well: is MBC1 only not supported? DDDDD999BBBB67636E0EECCCDDDC999FBBB9333E514958000000000000000000000000000000000101000001003F2606F3E080CD8C0021DC042A666FF92104002A5F2A57B328102A4F2A23232323E569:

**Comment by nensondubois** [comment]
The correct header should be: 0x143-14F: 80535700000000013302FDC7F1 and the GBS will add to the list of games. another issue though cosmetic is that if you add a ton of games it will leave one to two spaces in the listing.

**Comment by Infinest** [comment]
I've pushed a commit that should fix the incorrect spacing between ROMs if a certain number of ROMs is added to the list.
Regarding the other problem i still need what i stated in the first post. I don't know what "GBS PLAYER 3U" is...

**Comment by nensondubois** [comment]
Sorry for not explaining that part, I just assumed you had some exposure to it in some form to be familiar. GB2GBS is a program that converts GBS Game Boy Sound files to a working GB ROM and they can run on hardware via flash carts. That version has issues creating a mapper output with your program, the newer GBS2GB version does not have this issue.

**Comment by Infinest** [comment]
I'm assuming it's the program listed on this page?
http://www.angelfire.com/nc/ugetab/

I've gone ahead and generated a couple of GB files with all 3 version selections from Dracula Crazy Vampire.gbs, put them through the application with a bunch of other ROMs and everything generated fine. Even burnt it onto a cart and every singe ROM including the music ones played fine.

**Comment by nensondubois** [comment]
Yes. However, that is a newer version that works with writing GB conversions. Also, it seems that battery blocks are not displayed at the NP menu screen. I'm going to test more games and see if there are other issues because I feel like I remember seeing a game that isn't a conversion of a GBS that gave errors.

**Comment by Infinest** [comment]
I see. For now I'm going to assume this was some weird quirk with that version and close this issue for now.
In case you find any other concrete issue with an official game you can go ahead and open another issue.
