### ISSUE TITLE
Any way to remove the 1024k limit?

### ISSUE THREAD

**Issue by eisnerguy1** [Infinest/GB-Memory-Binary-Maker#5]
So, I'm trying to work on a semi-functional mockup of what Diakatana GB would've looked like in the GB Memory menu. I've got all 5 Daikatana GBC roms I thought this would be something cool to add. 
I had a few questions:
*Is there any way to modify the code so that it ignores the file size restraint? Like increasing the file size to 1152k.
If not, I modified [GBNP](https://orangeglo.github.io/gbnp/) to increase the file size to 1152k and that does the trick.
![](https://i.imgur.com/G5kzWHC.png)

*Where in the code, for GB Memory Binary Maker, is the [ticker text](http://forums.nesdev.com/viewtopic.php?f=12&t=11453&start=195)? I wanted to add actual text to the rom to make it look authentic.
*What Japanese font are you using for the ticker text and, can that be used for the game names as well? Or, could that be converted to a .woff font file?
When using "GB Memory Binary Maker", "大刀GB" just looks like this:
![](https://i.imgur.com/G9ZFfZ7.png)
Any help at all would be greatly appreciated.
Thanks!

**Comment by Infinest** [comment]
For the size limitations look into GB-Memory-Binary-Maker/GB Memory/Main.cs.
For the space limit for multiple roms + the menu itself `const int ROMSpace = 896` is used.
Separately, the function for generating MAP files for standalone ROMs without the menu `MAPButtonClick` in Main.cs also checks for a maximum size of 1024kB.
However, i do not now how functional the generated files will end up being if you disable the limit and go over it.

The application in it's current state does not support modifying the ticker text at the bottom. It will always keep the ticker text of the original menu binary you fed it.
The character set usable for ROM names is contained within `GB-Memory-Binary-Maker/GB Memory/Font.bmp`. All other characters will be ignored upon submit.
The characters coordinates within `Font.bmp` are defined in `GB-Memory-Binary-Maker/GB Memory/TitleImage.cs`.

What you want to do would required quite a bit of additional work on the code.

**Comment by eisnerguy1** [comment]
Ok, thanks for clearing all of that up.
